### PR TITLE
only use named exports, remove default export

### PR DESCRIPTION
**Pull request by philihp**
Brought up in #427, this will fix something that's frankly bugged me for a long time, to be released on the next major version update.

### CODE REVIEW

**Comment by philihp** [comment]
@ahkhanjani would this work for you?

**Comment by ahkhanjani** [comment]
Hey @philihp,

It seems like the internal `fastShuffle` function, here named `fnShuffle` is used to create the `shuffle` function. I'm just thinking, how about naming it `createShuffle`?

**Comment by philihp** [comment]
I like that, let's go with that.

**Comment by philihp** [comment]
Still thinking about this, I am prob gonna keep the default export as well for compatibility, but deprecate it and keep it removed from the readme

**Pull request merged**
